# Generated by Django 4.1.1 on 2022-10-01 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='tags',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
