# Generated by Django 4.1.1 on 2022-10-01 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_remove_blog_tags_delete_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='flag',
            field=models.ImageField(null=True, upload_to='country_flag'),
        ),
    ]
